apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "deployment-autoscaler.fullname" . }}-role
rules:
- apiGroups: ["*"]
  resources: ["deployments", "statefulsets", "replicasets"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]