apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "deployment-autoscaler.fullname" . }}-allow-autoscaler-edit-deployments
subjects:
- kind: ServiceAccount
  name: {{ include "deployment-autoscaler.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ include "deployment-autoscaler.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io