apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deployment-autoscaler.fullname" . }}
  labels:
    {{- include "deployment-autoscaler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "deployment-autoscaler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "deployment-autoscaler.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "deployment-autoscaler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: AUTOSCALE_NAME
              value: {{ .Values.autoscale_name }}
            - name: RABBITMQ_QUEUE
              value: {{ .Values.rabbitmq_queue }}
            - name: AUTOSCALE_KIND
              value: {{ .Values.autoscale_kind }}
            - name: AUTOSCALE_THRESHOLD
              value: "{{ .Values.autoscale_threshold }}"
            - name: AUTOSCALE_MAX
              value: "{{ .Values.autoscale_max }}"
            - name: AUTOSCALE_MIN
              value: "{{ .Values.autoscale_min }}"
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-connection-secret
                  key: uri
            {{- with .Values.extraEnv }}
{{ toYaml . | indent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
