plugins {
    id 'com.android.library'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.2"

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "0.9.7"
        ndk {
            abiFilters 'x86', 'armeabi-v7a', 'x86_64', 'arm64-v8a'
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"

        // Here's the version info:
        // see  https://developer.android.com/studio/publish/versioning
        archivesBaseName = "apollo-faceId-library"
        setProperty("archivesBaseName", "${archivesBaseName}-$versionName")

        // Heres's parameter for unit test
        buildConfigField "String", "TEST_PARAM1", "\"$TEST_PARAM1\""
        buildConfigField "String", "TEST_PARAM2", "\"$TEST_PARAM2\""
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path 'src/main/jni/CMakeLists.txt'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    androidTestImplementation 'androidx.test:rules:1.2.0' //needed for permssion in unit test
    androidTestImplementation 'com.android.support.test:rules:1.0.2'

    // Use below for project module 
    implementation 'org.tensorflow:tensorflow-android:1.13.1' // 1.13.0-rc0

    // Use below for fat-aar
    // embed 'org.tensorflow:tensorflow-android:1.13.1' // 1.13.0-rc0

}