image:
  repository: 604877064041.dkr.ecr.us-east-1.amazonaws.com/flask-apollo-processor

debug: 'True'

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    # Increase the default timeout from 60 to 300 so landmark-search jobs have time to complete
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300
  externalDnsHostname: api.apollo-cttso.com
  path: /*
  tls: true

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: 100m
    memory: 128Mi
#  limits:
#    cpu: 200m
#    memory: 264Mi

extraEnv: |
  - name: BUCKET_NAME
    value: "apollo-source-data"