image:
  repository: 604877064041.dkr.ecr.us-east-1.amazonaws.com/speaker-recognition

extra_shm: true

resources: 
  requests:
    cpu: 100m
    memory: 512Mi
  #limits:
  #  cpu: 100m
  #  memory: 512Mi
